### ISSUE TITLE
Add support for using tpope/vim-dispatch for running scp commands

### ISSUE THREAD

**Issue by jakubgs** [zenbro/mirror.vim#6]
Hi,

I'm loving this plugin but I do find the messages from scp annoying and distracting. I could really incorporate it into my workflow if it was less obtrusive. For that reason I would like to request support for running the scp commands with `Dispatch!` from [tpope/vim-dispatch](https://github.com/tpope/vim-dispatch) rather than using `!`. Like [here](https://github.com/zenbro/mirror.vim/blob/7250fcd1420545644cefeef550e13a4a2920aed9/autoload/mirror.vim#L207).

I would love to just wrap your commands like `MirrorPush` in `Dispatch` but unfortunately it only works for external commands, not vim commands.

Cheers,
Jacob

**Comment by jakubgs** [comment]
This just came to me, this could also be done with neovim's job-control. I guess that could be a separate issue.

**Comment by jakubgs** [comment]
I tried doing this myself by implementing this function in `mirror.vim`:

``` vim
function! s:ExecuteCommand(command)
  if exists(':Dispatch') == 2
    execute 'Dispatch!' a:command
  elseif
    execute '!' . a:command
  endif
endfunction
```

And then using it in a function like `PushFile()`:

``` vim
function! s:PushFile(env)
  let [port, local_file, remote_file] = s:PrepareToCopy(a:env)
  call s:ExecuteCommand(s:ScpCommand(port, local_file, remote_file))
  if !v:shell_error
    echo 'Pushed to' remote_file
  endif
endfunction
```

But for some reason the `echo` that is there causes the annoying

```
Press ENTER or type command to continue
```

I wonder why that is.

**Comment by zenbro** [comment]
Thank you for suggestions!
I also use neovim and would be happy to add job control support.
As for Dispatch support - I'll see what i can do.

**Comment by zenbro** [comment]
I tried to add support for dispatch.vim, but the result did not satisfy me.
First, execution of `:MirrorPush` via `:Dispatch` have same delay as the synchronous implementation.
Second, there is no success/fail callbacks. For example: after execution of `:MirrorPull`, I need to reload edited file only if it successfully updated. But the dispatch.vim can not give me this kind of information. He just opens a quickfix window with an error, if it happens.
Third, it can't catch user input (password prompt, etc.). This problem is solved by using passwordless authentication via ssh-keys but it breaks backward compatibility with synchronous implementation.
You can try it yourself, here is the code:

``` diff
diff --git a/autoload/mirror.vim b/autoload/mirror.vim
index 936e7a7..5029843 100644
--- a/autoload/mirror.vim
+++ b/autoload/mirror.vim
@@ -201,13 +201,24 @@ function! s:OpenRootDir(env, command)
   execute ':' . a:command printf('scp://%s//', host)
 endfunction

+function! s:ExecuteCommand(command, message)
+  if exists(':Dispatch') == 2
+    execute 'Dispatch' a:command
+    echo a:message
+  else
+    execute '!' . a:command
+    if !v:shell_error
+      echo a:message
+    endif
+  endif
+endfunction
+
 " Overwrite remote file with currently opened file
 function! s:PushFile(env)
   let [port, local_file, remote_file] = s:PrepareToCopy(a:env)
-  execute '!' . s:ScpCommand(port, local_file, remote_file)
-  if !v:shell_error
-    echo 'Pushed to' remote_file
-  endif
+  let command = s:ScpCommand(port, local_file, remote_file)
+  let message = 'Pushed to ' . remote_file
+  call s:ExecuteCommand(command, message)
 endfunction

 " Overwrite local file by remote_file
```

Instead of dispatch.vim, I added support for neovim job control (166060135f4af3a73d969f7de9cf2dd6791d44f1) and it works perfectly. :smiley:

**Comment by jakubgs** [comment]
Oh man, that's glorious. I'm currently on a trip back home, once I return and I'm in the office on the 4th I'll check it out. Thanks a bunch! I REALLY appreciate it. Without people like you vim/neovim wouldn't be half as cool as it is.

**Comment by zenbro** [comment]
@PonderingGrower thank you for your help and inspiration!

**Comment by zenbro** [comment]
I will close this issue for the reasons stated above.
